### ISSUE TITLE
Dry-run for contract updates

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1035]
neofs-adm updates contracts one by one. If one contract fails, then previous contracts won't be roll backed. This makes updating a bit more complicated if one contract fails to update. Then we should prepare custom version of the contracts, where `update` is ignored for already updated contracts. 

Maybe we can do test invokes for all contracts before sending actual transactions to the network. `--dry-run` flag will be very appreciated.

**Comment by roman-khimov** [comment]
How about combining updates in a single transaction (it of course it doesn't overflow the script size)? Then any of the updates failing will fail whole transaction and consequently any previous updates made by the same transaction.

**Comment by fyrchik** [comment]
Initially, all updates were split because combining them in one transaction lead to manual GAS calculations, which complicated CLI (hardcoding them is not really an option).
Having all of this in one transaction (GAS can be calculated as sum of the cost of separate test-invokes + small addend) will also simplify resume-aborted-update logic (for every contract we check if it has already been updated).
