### ISSUE TITLE
Problem in child object delete

### ISSUE THREAD

**Issue by ZhangTao1596** [nspcc-dev/neofs-node#1050]
## Is your feature request related to a problem? Please describe.
Currently we only check the `SplitInfoError` in https://github.com/nspcc-dev/neofs-node/blob/11466ea3ccc5f60469d11f2100db69f34c5bd6ec/pkg/services/object/delete/util.go#L41-L54 ignoring the parent of object. And user can get child object id via object search request. So that user can only delete a child object which makes the object incomplete.

## Describe the solution you'd like
Check whether object has parent.

## Describe alternatives you've considered
Stop user only deleting a child object.

**Comment by alexvanin** [comment]
While it is a good approach for systems with centralized control pane, I don't think this is a suitable solution for decentralized storage. 

I agree that users should not be able to remove parts of objects. However, this should be implemented on the application side, while low-level API provides a predictable set of actions for every object. DApps and services should encapsulate the abstraction of object splitting and provide an interface only for root objects.

The main issue with implementing such restrictions in low-level API is that it creates _unremovable_ objects. All objects should be treated equally as much as possible to provide a predictable API. In a decentralized system, one can create object parts by settings corresponding headers manually, node can't control everything everywhere. And nobody will be able to remove such objects unless local GC will drop them. 

I think it is better to keep the possibility to remove object parts in low-level API rather than having unremovable objects in the system. Let's see for other opinions on that.

**Comment by alexvanin** [comment]
Closing, according comment above. Reopen or link this issue in case of related issues or proposals.
