### ISSUE TITLE
Wallet's password shouldn't be asked if it's empty.

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#1107]
... like in the following examples:
```
Debian GNU/Linux bookworm/sid host tty1

host login: user
user@host:~$
```
```
$ ssh user@host
user@host:~$
```

Added by @realloc 

In `neofs-cli`, let's add a step trying to access wallet using an empty password, if there is no password set by any other means (config, argument, environment variables, etc). If this fails, ask it interactively.

**Comment by fyrchik** [comment]
After #1103 we can set password config. Is it enough?
I don't like the idea of trying to decode with empty password first because this makes our interactive app less responsive for most of the users in order to cover a very narrow use-case. Plus, the current behaviour is consistent and contains no corner cases.

**Comment by 532910** [comment]
Nope. For example openssl or gnutls-bin don't ask for a password if key is unecrypted.

**Comment by anatoly-bogatyrev** [comment]
In my personal opinion, such additional actions to verify whether the wallet is encrypted with an empty password or not, so as not to ask for the password in the case of an empty one, will complicate the logic where it is not needed. It would be preferable to always ask for a password. This is unambiguous behavior.

**Comment by cthulhu-rider** [comment]
@532910 please fill an issue body with suggested solution.

**Comment by fyrchik** [comment]
I propose to implement this and add `--ask-password` option to always ask for password.

**Comment by realloc** [comment]
In neofs-cli, let's add a step trying to access wallet using an empty password, if there is no password set by any other means (config, argument, environment variables, etc). If this fails, ask it interactively.

**Comment by fyrchik** [comment]
1. Both openssl, ssh have allow to _create_ password-less keys. They have different file format (not encrypted at all https://github.com/openssh/openssh-portable/blob/d9dbb5d9a0326e252d3c7bc13beb9c2434f59409/sshkey.c#L3927). This is not what we have here, `neo-go` doesn't allow unencrypted wallets by design. `openssl genrsa` password can't be less than 4 characters, `openssl enc` doesn't encrypt anything if empty password is provided.
2. This introduces inconsistent behavior, if I write some scripts/pipelines I expect them to work properly without any hassles even if the password is empty.
3. This performs unnecessary work which makes CLI less responsive (well, on some machines). Password-less wallet isn't even a common case, just some testing setup.
4. #1136 allowed to use empty password from config file. I really fail to understand why this is not an option.

**Comment by cthulhu-rider** [comment]
* see also https://github.com/nspcc-dev/neo-go/issues/2387

**Comment by roman-khimov** [comment]
Not needed.
