### ISSUE TITLE
Make shard read-only on errors

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#1118]
As described in https://github.com/nspcc-dev/neofs-node/issues/1094#issuecomment-1018259445, there are many places where unexpected error is encountered during shard operation. We can make shard read-only in this situation, carefully checking that this is indeed a reasonable action for all possible errors returned.

Related #1115 .

**Comment by realloc** [comment]
Indeed, we need this to properly detect failed disk state.
I'd suggest adding an option like `shard_ro_error_threshold` to regulate this behaviour. If set to `0`, shard will never be switched to R/O mode, other values would force RO state after accumulating the desired number of errors.

I'm not sure about using the rate instead of threshold, as it's more complicated but the particular use-case is not clear.
