### ISSUE TITLE
Node can store potentially undead objects

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#1226]
## Context
Object removal in NeoFS is performed using special objects of type [TOMBSTONE](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/object/types.proto#L25). These objects are stored physically just like all other objects. In order to solve some issues related to object removal in distributed systems, tombstones they are initially broadcast throughout the container. Nodes from a primary placement store tombstones physically, while all others only record a note that they learned about the intention to delete the object. These removal records are written in local object storage:
https://github.com/nspcc-dev/neofs-node/blob/14ea7b2c473a7be1f249225fad9f789cbd32971f/pkg/local_object_storage/metabase/inhume.go#L72

## Overview
In the current implementation, the storage node may miss the death of the object and continue to store it locally, and later distribute it throughout the container. This could be due to two reasons:

1. the node missed the appearance of the tombstone in the container (primarily due to network problems)
2. the node has marked the object as removed (`Inhume` operation mentioned above) and this entry will never expire

While `1` can't be completely solved in distributed container, `2` is caused by the loss of expiration date in local record.

## Proposed solution
We need to extend logic of local object storage and GC.  First of all we need to track expiration dates of tombstones in local object storage:
```
func (*InhumePrm) ExpiresAfter(epoch uint64)
```
After removal records became limited in lifetime, we need to be able to process expiration dates:
```
// method to be implemented
func (Grave) ExpiresAfter() uint64

// the method's usage
func (*DB) IterateOverGraveyard(h GraveHandler) error
```
These changes will allow `GC` to process grave expiration timestamps
https://github.com/nspcc-dev/neofs-node/blob/14ea7b2c473a7be1f249225fad9f789cbd32971f/pkg/local_object_storage/shard/gc.go#L185

As a consequence, an additional improvement will be the separation of expired tombstones as objects and expired grave records.

### Other objects
[LOCK](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/object/types.proto#L31) objects behave similar to `TOMBSTONE` ones (except to prevent deletion), so we need to process them almost the same. We've encountered same problems in 
* https://github.com/nspcc-dev/neofs-node/pull/1181

**Comment by alexvanin** [comment]
After internal discussion, we've decided that current behavior is invalid, when storage engine drops object payload on tombstone removal. Instead, object engine should remove object payload as soon as GC observes record in `tombstone` bucket (or send it into the queue, but we don't have queues yet). 

However we explicitly implemented different behavior in current storage engine. The reasons for that are kinda lost. So in this issue we need:
- [ ] verify that object removal based on tombstone record appearance is valid 
- [ ] if so, implement it in node, otherwise discuss the reasons why it is invalid and review proposed solution.

**Comment by carpawell** [comment]
In the current implementation, tombstones are broadcasted to the whole container and all are saved to the local storage. However, they are deleted by `policer` due to the `redundant local object copy detected` rule. IMO, tombstones should not be deleted by the container nodes and should have been being stored until their expiration. This would help with instant physical object removal.

Now it works as the following:
1. Node receives tombstones, stores info about their object in the graveyard, and stores the tombstone.
1.1. \**if node not in the placement*\* Node deletes tombstones.
2. Node deletes objects covered by the tombstones using info from the graveyard when the tombstones expire.
3. Node deleted graveyard row about just deleted object.
4. Node marks the tombstones with GCMark.

My suggestion (tombstones are not deleted by the node's policer):
1. Node receives tombstones, stores info about their object in the graveyard, *marks covered object with GCMark* and stores the tombstone.
1.1. GC deletes objects *but does not touch the graveyard*.
1.2. Node says `object not found` on `Get` because of the raw in the graveyard.
2. Node clears the graveyard when the tombstones expire.
4. Node marks the tombstones with GCMark.

#### Why storing tombstones would help:
0. It is logically more accurate to store info about the deleted object (that could potentially come to a node) the same way as it is done by the placement node, IMO.
1. It saves from metabase changes: it would not be storing info about tombstones expiration that it does not have (I mean we would not implement the suggestion from the issue). 
2. There would not be situations when the node stores tombstones (writecache, meta, blobstor; the whole cycle) to just fill the metabase and then delete it. (Yes that could be changed, but not it works this way).
3. We just cannot change the lazy-delete approach without additional metabase changes (rise of the dead).
