### ISSUE TITLE
Limit amount of incoming connections

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1240]
It seems that bottleneck caused by https://github.com/nspcc-dev/neofs-node/pull/1236 leads to node goroutine overload and OOM: if request intensity is high enough to hit application limits (goroutine limit), then storage node is going to be killed by OS. 

The better option is to provide some kind of limits in config and do not accept new incoming connections in case of high load.

**Comment by fyrchik** [comment]
This setting can influence default metabase boltdb batch size: if there are no more than X parallel operations on shard, there is no reason to have batch size >X, we better use `X / shard_count` in this case.

**Comment by fyrchik** [comment]
GRPC doesn't allow to limit this amount directly, though we can try to restrict the waiting queue.
I have 2 solutions in mind:
1. Maintain a counter for the amount of operations being executed, fail request immediately if the counter exceeds a threshold.
2. Introduce a pool instead of launching new goroutine, submit task, fail if it hasn't started to execute in 2 seconds (any other time).

Also we better solve this on a case-by-case basis.
