### ISSUE TITLE
Storage node saves invalid object with dup attributes in local storage

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1286]
## Expected Behavior
Storage node does not save invalid object with duplicated attributes 

## Current Behavior
Storage node does save such object locally and tries to replicate it unsuccessfully. 

## Possible Solution
Check formatting before saving object locally

## Steps to Reproduce (for bugs)

1. Launch dev-env
2. Create container with REP 4 policy.
3. Upload object with duplicated attributes. Get en error
4. See how remote node tries to replicate invalid object because it saved it locally.

Partially related to https://github.com/nspcc-dev/neofs-node/issues/1283

## Your Environment
neofs-node v0.27.7

**Comment by cthulhu-rider** [comment]
We can conditionally divide the fields of an object into user and system fields. In the described scenario, the system data is set correctly according to the protocol and network configuration, and the user data is not processed (user attributes in particular).

## Possible solution
Define two kinds of validators: user-only and system-only. Before we start to process any object in `putsvc.Service` it is checked by user-only validator. If saving is trusted (session token is provided) we skip system checks.

Regarding the repetition of attributes:

- hard (current): refuse service
- semi-hard: refuse service if values are different, otherwise drop the repetitions
- soft: remove all thee repetitions and leave, for example, the 1st attribute

IMO hard check is better since it requires careful setting of attributes by the user and hides fewer potential bugs.
