### ISSUE TITLE
WS morph client in CLIs

### ISSUE THREAD

**Issue by carpawell** [nspcc-dev/neofs-node#1378]
After #1170 morph client [uses](https://github.com/nspcc-dev/neofs-node/blob/d99800ee93bbe9b0699313ba7a5ecab85699731c/pkg/morph/client/client.go#L46) WebSocket neo-go client (and only it, it could not accept HTTP endpoints at all). Some CLI commands continued accepting HTTP addresses since they [use](https://github.com/nspcc-dev/neofs-node/blob/d99800ee93bbe9b0699313ba7a5ecab85699731c/cmd/neofs-adm/internal/modules/morph/n3client.go#L22) raw neo-go client and some CLI commands started requiring WebSocket addresses.

So, at least:
1. Sync their behavior (or discuss why is that ok to accept different endpoints);
2. Check that written documentation/usage help is actual.

**Comment by carpawell** [comment]
IMO[1], using WS in CLI is strange.

IMO[2], writing another wrapper around neo-go client just because of IMO[1] is strange.

**Comment by alexvanin** [comment]
> and some CLI commands started requiring WebSocket addresses.

What exact command, just wonder?

**Comment by carpawell** [comment]
> What exact commands, just wonder?

In the `neofs-adm` any related to the subnet management, e.g. `neofs-adm morph subnet create`.

**Comment by fyrchik** [comment]
The purpose of using `WSClient` is to have less overhead for a consistent request flow. `neofs-adm` is a bit different, because we spend most time waiting for the transactions, and the amount of requests for any command has the order of 10, not 1000.

However, in #1302 the client interface is introduced, so it shouldn't be hard to use `WSClient` and/or fallback to the simple client if websockets are not supported. The scope is intentionally limited (and can be further reduced), so writing a wrapper shouldn't be hard if needed.
