### ISSUE TITLE
About networking pricing ?

### ISSUE THREAD

**Issue by rkonfj** [nspcc-dev/neofs-node#1435]
When I deploy storage nodes, it costs me a lot of network traffic.
Like storage capacity, is there a price for network traffic?

**Comment by realloc** [comment]
Right now we don't account/bill network traffic because we didn't find a good way to do it yet.

In untrusted environment we need some way for other network participants to verify node's traffic consumption claims. While we have a data audit process for storage consumption claims, we are still searching for a process with similar trust guaranties for traffic accounting. Any ideas are welcome!

**Comment by roman-khimov** [comment]
Nothing we can do here for now.
