### ISSUE TITLE
[0.28.3]: `neofs-cl object hash` on system keys' behalf fails more often than usual 

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neofs-node#1512]
I've been running integration tests through the devenv with 0.28.3 version of NeoFS. Approximately 2 times of 3 `neofs-cli object hash` failed with `2049 = object not found` error when request is performed on behalf of Storage Node or Inner Ring. This problem is actual for simple and complex object. No special environment or request parameters was arranged, it was regular requests from integration tests. I've been observing the fails when running tests from the [PR](https://github.com/nspcc-dev/neofs-testcases/pull/237/)

## Your Environment
Nodes from neofs-dev-env 0.28.3, neofs-cli 0.28.3

**Comment by cthulhu-rider** [comment]
I suppose the problem is in spawning `RANGE` request during `HASH` processing (see ACL spec). When the request gets to the node with the object - it fulfills, because new requests are not generated. Otherwise, an access error is thrown. Why 404 error then? At the moment, the node returns a composite error without a trace.

Total: if you wish to allow `HASH` op, you need to allow `RANGE` and `HEAD` ops.

**Comment by fyrchik** [comment]
I have checked this and yes, the problem it in the ACL itself. Probably, we could fallback to using `GETRANGEHASH` if `GETRANGE` is denied by the basic ACL.

**Comment by fyrchik** [comment]
We have done similar thing for `GET_RANGE` which fallback to `GET`.
Let's also do it here.

**Comment by roman-khimov** [comment]
Looks like #2144/#2541 duplicate.
