### ISSUE TITLE
Sometimes neofs-adm fails to tick epoch

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-node#1671]
The issue is intermittent, does not occur on every run. We face it when we run the following 

## Steps to Reproduce (for bugs)
1. Create a container
2. Put new object into the container via http gateway. Specify attribute `X-Attribute-Neofs-Expiration-Epoch`.
3. Tick epoch using neofs-adm: `neofs-adm morph force-new-epoch -c /.setup/config.yaml`
4. Tick epoch again: neofs-adm: `neofs-adm morph force-new-epoch -c /.setup/config.yaml`

## Expected Behavior
Tick epoch works both on step 3 and 4.

## Current Behavior
Tick epoch sometimes fails on step 3 or step 4 (attached is the [log of test run](https://github.com/nspcc-dev/neofs-node/files/9289858/test-log.txt) for the case when it failed on step 4).
Observed behavior is that neofs-adm process returns code 1.

Probably there is some timeout happening while neofs-adm tries to push a transaction for new epoch. We started `force-new-epoch` at 19:09:05 and at 19:09:40 we've got an error. Please, find attached the logs of 4 inner ring nodes:
[ir-log-az.txt](https://github.com/nspcc-dev/neofs-node/files/9289852/ir-log-az.txt)
[ir-log-buky.txt](https://github.com/nspcc-dev/neofs-node/files/9289855/ir-log-buky.txt)
[ir-log-glagoli.txt](https://github.com/nspcc-dev/neofs-node/files/9289856/ir-log-glagoli.txt)
[ir-log-vedi.txt](https://github.com/nspcc-dev/neofs-node/files/9289857/ir-log-vedi.txt)

## Your Environment
4 cloud VMs with 4 consensus nodes and inner ring nodes.

* Version used:
v0.31.0

**Comment by fyrchik** [comment]
Supposedly, IR ticked the epoch at the same time (it received a notification at 19:03, neofs-adm was executed at 19:05). 

There are 2 ways to approach this:
1. Ensure the epoch is ticked anyway.
2. Skip manual tick if automatic tick was done.

The second approach is more reliable, because ticking the epoch twice can lead to unexpected consequences.

It is hard to tell, why we waited for persist without neo-go node logs:
1. If the IR transaction had is the same hash, we should've been able to get the result.
2. If the hash was different, our tx _could've been_ removed from the mempool because of `ValidUntilBlock` field (i.e. by default it is equal to `current height + 2`, hard to tell without logs.

**Comment by fyrchik** [comment]
Actually, the second approach is also error prone, because we still have a race condition: there is some time between calculating execution gas cost and sending the transaction. `neofs-adm` will fail with a message containing `invalid epoch`.

**Comment by roman-khimov** [comment]
Concurrent manual & automatic ticks can lead to undefined behaviour. Not a huge deal since manual ticks are very much special and can be retried if needed.
