### ISSUE TITLE
Tree service ignored object expiration

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-node#1695]
When there is an object added to the hierarchy in TreeService and it gets expired, Tree Service does nothing with it.

The expected behavior is to catch expiration notification and produce a correct set of changes in the tree removing the corresponding leaf.

**Comment by fyrchik** [comment]
There are 2 problems here:
1. For containers of multiple nodes it could be hard to ensure that the operation is produced once.
I guess some duplication is ok, if the total amount of _replicas_ is small.
2. Deleting a file can involve deleting it's automatically created parents. It's tricky, because locally generated timestamp can conflict (be higher) than the timestamp for a new not-yet-replicated operation from other node.

**Comment by fyrchik** [comment]
We can make our GC to remove nodes from the tree service when an object expires.

**Comment by roman-khimov** [comment]
Trees will be removed, this issue will never be done.
