### ISSUE TITLE
Messages about system throttling should be more informative

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#1937]
If I start k6 load with 100 VUs I get a lot of errors: ```rpc error: context deadline exceeded```. It means that system is throttling with 100 VUs. Because if I use 50 VUs I don't see those errors.
But this not understandable from error message.

We should make error message more understandable.

**Comment by fyrchik** [comment]
This error can occur because of many different reasons, I don't think we can make it more informative.
Basically client has waited for too long without receiving an answer from the node.

**Comment by cthulhu-rider** [comment]
From client perspective the error is expected as @fyrchik said: this is not a server response, this is an absence of server response after certain period of time.

All we can do is to create dedicated status for resource exhaustion and make server to analyze local resource quota. But it won't work stable anyway since:
- timeout can be too short
- load analysis will be quite far from the exact values

**Comment by roman-khimov** [comment]
Timeout is a timeout.
