### ISSUE TITLE
Who deploys contracts in auto-deploy procedure?

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-node#2418]

**Comment by AnnaShaleva** [comment]
There are two points of view:
1. At the start of auto-deploy procedure each alphabet node looks for the required neofs contracts in the chain and if contracts are missing, each node sends deployment transaction signed by its simple signature account independently from the other nodes.
2. At the start of auto-deploy procedure single designated alphabet node (let it be AZ) looks for the required neofs contracts in the chain and if contracts are missing, AZ sends the deployment transaction, whereas rest of the committee wait for the contracts to be deployed.

In the case 1 we may end up in a situation when multiple versions of a single contract will be deployed. In case 2 there's a risk of centralisation (AZ may be killed during setup which will cause failure of the whole deployment procedure).

I vote for case 2. I consider that contracts auto-deployment procedure is the part of the network setup, and network setup is something that should be performed on a *stable* network. If we don't like the fact that single node is responsible for all contracts deployment, then we may add some definite round-robin algorithm accoarding to which each node will deploy contract at her own time. E.g. AZ is allowed to deploy contracts from block 0 till block 5 (we should set VUB of deployment transactions to 5); after that, if the contracts still not deployed, than BUKY should send the deployment transaction within 5-th and 10-th blocks, etc...

I don't quite like case 1, because it produces a lot of on-chain garbadge (duplicating deployed contracts that will never be used), and this situation can be avoided.

**Comment by AnnaShaleva** [comment]
Ref. https://github.com/nspcc-dev/neofs-node/pull/2408.

**Comment by roman-khimov** [comment]
For initial deployments `az` dependency is OK. It's less so for updates and other activities during the network regular operation. Rotating speakers is an acceptable solution, but reusing proxy for the sender and always creating identical transactions on each of participating nodes is preferable.

**Comment by AnnaShaleva** [comment]
> For initial deployments az dependency is OK

Yep, this issue is only about deploument procedure, we don't need this for update, because we aleady have Proxy contract when updating the contracts.

**Comment by roman-khimov** [comment]
OK, so if this issue is about initial deployments, then I guess it's solved.
