### ISSUE TITLE
BasicACLErr and eACLErr errors are created incorrectly

### ISSUE THREAD

**Issue by Ayrtat** [nspcc-dev/neofs-node#2465]
## Expected Behavior

An error created by the method [basicACLErr](https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/acl/v2/errors.go#L27C1-L27C1) or [eACLErr](https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/acl/v2/errors.go#L34C6-L34C13) must be able to be casted to 
```
var errAccessDenied *apistatus.ObjectAccessDenied
```

## Current Behavior

It seems `getObject` method for object service works incorrectly [here](https://github.com/nspcc-dev/neofs-node/blob/cd628f77ac350332c61e446f542aa1a8e3904bdc/pkg/services/object/get/util.go#L146) because the casting `errors.As(err, &errAccessDenied)` doesn't work out

## Possible Solution

https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/acl/v2/errors.go#L28
https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/acl/v2/errors.go#L35
`var errAccessDenied apistatus.ObjectAccessDenied` should be replaced with `errAccessDenied := &apistatus.ObjectAccessDenied{}`

## Steps to Reproduce (for bugs)

You can check it with unit-test 

```golang
func TestBasicACLErr(t *testing.T) {
	var reqInfo RequestInfo
	err := basicACLErr(reqInfo)

	var errAccessDenied *apistatus.ObjectAccessDenied

	require.ErrorAs(t, err, &errAccessDenied,
		"basicACLErr must be able to be casted to apistatus.ObjectAccessDenied")
}
```

**Comment by cthulhu-rider** [comment]
these code spaces are executed on different processes - [this](https://github.com/nspcc-dev/neofs-node/blob/cd628f77ac350332c61e446f542aa1a8e3904bdc/pkg/services/object/get/util.go#L146) on one node-as-client, [this](https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/acl/v2/errors.go#L27C1-L27C1) on another node-as-server. So, type mismatch must not affect behavior

**Comment by roman-khimov** [comment]
I think we can still check our `error.As` uses and try converting them to `error.Is` using new SDK types and instances, those work fine both for simple instances and pointers. And the code will likely be a bit more readable this way.

**Comment by Ayrtat** [comment]
> these code spaces are executed on different processes - [this](https://github.com/nspcc-dev/neofs-node/blob/cd628f77ac350332c61e446f542aa1a8e3904bdc/pkg/services/object/get/util.go#L146) on one node-as-client, [this](https://github.com/nspcc-dev/neofs-node/blob/master/pkg/services/object/acl/v2/errors.go#L27C1-L27C1) on another node-as-server. So, type mismatch must not affect behavior

Sorry, I didn't get the point. The client code invokes [PayloadRange](https://github.com/nspcc-dev/neofs-node/blob/cd628f77ac350332c61e446f542aa1a8e3904bdc/pkg/services/object/get/util.go#L143C36-L143C36) that gets a response from server side. And server returns wrapped  `basicACLErr` error that is failed to get casted to `apistatus.ObjectAccessDenied`

**Comment by cthulhu-rider** [comment]
@Ayrtat i mean [this](https://github.com/nspcc-dev/neofs-node/blob/cd628f77ac350332c61e446f542aa1a8e3904bdc/pkg/services/object/get/util.go#L143C36-L143C36) calls client [method](https://github.com/nspcc-dev/neofs-sdk-go/blob/515748dc50cb069daa092532f2d0db520feb8338/client/object_get.go#L607) and it must handle client's claimed return no matter what the server returns

as @roman-khimov said, we just inaccurately updated to a NeoFS SDK RC-9 that changed the documentation of returned errors: [actual](https://github.com/nspcc-dev/neofs-sdk-go/blob/515748dc50cb069daa092532f2d0db520feb8338/client/object_get.go#L561-L569) instead of [previous](https://github.com/nspcc-dev/neofs-sdk-go/blob/8ed98d6dec2a4305d11612cbc22a3b30ff55e125/client/object_get.go#L623-L630)
