### ISSUE TITLE
Try autoupdating the network

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-node#2650]
With #2642 solved we can try autoupdate functionality of the network:
 * run an old (0.38.0) network with dev-env (contracts 0.17.0)
 * create some containers, push some objects into it
 * update IR binaries to the current master builds
 * check contracts that should be auto-updated (`neofs-adm morph dump-hashes`)

**Comment by evgeniiz321** [comment]
@roman-khimov updating of the running env is a little bit tricky. Need help with these 3 questions.

1. Currently in a running env we also have a morph-chain. Besides updating IR binaries we also need to update IR config and storage nodes config (since they use morph-chain). What is the expected update procedure? Do I really need to update configs, do some other things (like removing morph-chain), or it should work just with a new binary?
2. Storage nodes can't be recreated currently as is (perhaps I'm missing the right way to restart them, but I can't create them from scratch since I have containers with objects there)- I see these errors:

`2023/11/20 20:46:49 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory
2023/11/20 20:47:06 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory
2023/11/20 20:47:23 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory
2023/11/20 20:47:35 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory
2023/11/20 20:47:54 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory
2023/11/20 20:48:07 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory
2023/11/20 20:48:21 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory
2023/11/20 20:48:35 can not create (ensure it exists) dir by '/storage/peapod0.db' path: mkdir /storage/peapod0.db: not a directory`
What is the proper way of updating storage nodes ? or is this a bug? 

3. In tests I'm getting this error after IR update (without storage node config updates, so they keep using old morph-chain):

`E           RuntimeError: Failed to init s3 credentials because of error
E           Could not find AWS credentials in output:
E           Enter password for /home/ezayats/neofs-testcases/TemporaryDir/18e74049-c35a-470f-aec9-0d0b070f0b63.json >
E           2023-11-20T20:41:57.564Z	DEBUG	s3-authmate/main.go:703	prepare connection pool
E           2023-11-20T20:41:57.578Z	INFO	authmate/authmate.go:235	check container or create	{"cid": "11111111111111111111111111111111", "friendly_name": "b17c489e-2120-46ba-bdc6-b3f215594d3a", "placement_policy": "REP 2 IN X CBF 3 SELECT 2 FROM * AS X"}
E           failed to issue secret: check container: create container in NeoFS: save container via connection pool: put: status: code = 1024 message = chain/client: contract execution finished with state FAULT; exception: at instruction 2034 (THROW): unhandled exception: "insufficient balance to create container"` 
Also not sure why the balance went away somewhere, is it a bug, or do I need to do some refills here?

**Comment by roman-khimov** [comment]
1. morph-chain is not affected. It'll be internalized eventually like in nspcc-dev/neofs-dev-env#282, but for this test it can work as is, not requiring any changes.
2. Looks like 0.38.0 bug which was fixed in 0.38.1. So you need to start from 0.38.1.
3. That's strange, if you have something before the upgrade it can't evaporate. Maybe you've effectively restarted the chain.

**Comment by roman-khimov** [comment]
This just means that you've got a new chain and this is exactly what should be avoided. You need to keep IR configuration with separated CNs.

**Comment by evgeniiz321** [comment]
@roman-khimov without consensus parameters in an IR config there is no autoupdate (https://github.com/nspcc-dev/neofs-node/blob/master/pkg/innerring/innerring.go#L362), so contracts stay the same. When consensus parameters are specified - we get 2 chains

**Comment by cthulhu-rider** [comment]
> contracts stay the same

@evgeniiz321 pls describe how do you check this?

**Comment by roman-khimov** [comment]
@cthulhu-rider: but if it's `false`, it's supposed to operate normally with the contracts currently on the network, right? IIUC it doesn't start at all right now.

**Comment by cthulhu-rider** [comment]
> operate normally with the contracts currently on the network, right?

yep, but then all contracts must be deployed in advance (which hasn't been done according to `Unknown contract` error)

@evgeniiz321 pls share used config

**Comment by cthulhu-rider** [comment]
@evgeniiz321 i dont see `fschain_autodeploy` flag. That means Inner Ring expects all contracts to be deployed before the app startup moment

do u preset some file by `./db/morph.bolt` path or starting from scratch?

**Comment by evgeniiz321** [comment]
1. I started dev-env from scratch as it is in master.
2. Then updated config:
```
# Logger section
logger:
  level: debug  # Minimum enabled logging level

# Wallet settings
wallet:
  path: /wallet.json  # Path to NEP-6 NEO wallet file
  address: Nhfg3TbpwogLvDGVvAvqyThbsHgoSUKwtn  # Account address in the wallet; ignore to use default address
  password: one  # Account password in the wallet

# Profiler section
pprof:
  enabled: true
  address: :6060  # Endpoint for application pprof profiling; disabled by default
  shutdown_timeout: 30s  # Timeout for profiling HTTP server graceful shutdown

# Application metrics section
prometheus:
  enabled: true
  address: :9090  # Endpoint for application prometheus metrics; disabled by default
  shutdown_timeout: 30s  # Timeout for metrics HTTP server graceful shutdown

# Toggling the sidechain-only mode
without_mainnet: false

# Neo main chain RPC settings
mainnet:
  endpoints: # List of websocket RPC endpoints in mainchain; ignore if mainchain is disabled
    - ws://main-chain:30333/ws

# Neo side chain RPC settings
morph:
  endpoints: # List of websocket RPC endpoints in sidechain
    - ws://morph-chain:30333/ws
  validators:  # List of hex-encoded 33-byte public keys of sidechain validators to vote for at application startup
    - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2

fschain_autodeploy: true

network_settings: # NeoFS network settings managed in the Netmap contract
  epoch_duration: 240 # Time interval (approximate) between two adjacent NeoFS epochs measured in Sidechain blocks.
  # Must be an integer in range [1, 18446744073709551615]
  max_object_size: 67108864 # [bytes] Maximum size of physically stored NeoFS objects. Note that this applies
  # only to objects located on storage nodes: user objects have no restrictions and, if necessary, are sliced.
  # Must be an integer in range [1, 18446744073709551615]
  require_homomorphic_hashing: true # Toggles the requirement for homomorphic hashing of object payloads.
  # Must be 'true' or 'false'
  allow_maintenance_mode: true # Toggles permission to transition storage nodes to maintenance state.
  # Must be 'true' or 'false'
  eigen_trust:
    alpha: 0.1 # Alpha parameter of EigenTrust algorithm used in the Reputation system.
    # Must be a floating point number in range [0, 1].
    iterations_number: 4 # Number of EigenTrust algorithm iterations to pass in the Reputation system.
    # Must be an integer in range [1, 18446744073709551615]
  price: # Price settings. NEOFS means NeoFS Balance contract tokens (usually GASe-12).
    storage: 100000000 # [NEOFS] Price for 1GB of data paid every epoch by data owner to storage nodes.
    # Must be an integer in range [0, 18446744073709551615]
    fee:
      ir_candidate: 100 # [GASe-8] Contribution from the new candidate to the Inner Ring. Must be non-negative integer
      # Must be an integer in range [0, 18446744073709551615]
      withdraw: 100000000 # [GASe-8] Fee paid by the user account to;
        # - NeoFS Processing contract (if Notary service is enabled in the NeoFS Mainchain)
      # - each Alphabet member (otherwise)
      # Must be an integer in range [0, 18446744073709551615]
      audit: 10000 # [NEOFS] Fee for data audit paid by storage group owner to the auditor (Inner Ring member).
      # Must be an integer in range [0, 18446744073709551615]
      new_container: 1000 # [NEOFS] Fee for new container paid by creator to each Alphabet member.
      # Must be an integer in range [0, 18446744073709551615]
      container_domain: 500 # [NEOFS] Fee for container's NNS domain paid by container creator to each Alphabet member.
      # Must be a non-negative integer
  custom: # Optional list of custom key-value pairs to be set in the network configuration. Forbidden keys:
    # [AuditFee, BasicIncomeRate, ContainerAliasFee, ContainerFee, EigenTrustAlpha, EigenTrustIterations, EpochDuration,
    # HomomorphicHashingDisabled, InnerRingCandidateFee, MaintenanceModeAllowed, MaxObjectSize, WithdrawFee]
    # Note that this list can be extended in the future, so, to avoid potential collision, it is recommended
    # to use the most specific keys.
    - my_custom_key1=val1
    - my_custom_key2=val2

nns:
  system_email: ops@nspcc.io

# Network time settings
timers:
  emit: 50  # Number of sidechain blocks between GAS emission cycles; disabled by default
  stop_estimation:
    mul: 1  # Multiplier in x/y relation of when to stop basic income estimation within the epoch
    div: 4  # Divider in x/y relation of when to stop basic income estimation within the epoch
  collect_basic_income:
    mul: 1  # Multiplier in x/y relation of when to start basic income asset collection within the epoch
    div: 2  # Divider in x/y relation of when to start basic income asset collecting within the epoch
  distribute_basic_income:
    mul: 3  # Multiplier in x/y relation of when to start basic income asset distribution within the epoch
    div: 4  # Divider in x/y relation of when to start basic income asset distribution within the epoch

# Storage node GAS emission settings
emit:
  storage:
    amount: 1000000000  # Fixed8 value of sidechain GAS emitted to all storage nodes once per GAS emission cycle; disabled by default

# Storage node removal settings
netmap_cleaner:
  enabled: true  # Enable voting for removing stale storage nodes from network map
  threshold: 3  # Number of NeoFS epoch without bootstrap request from storage node before it considered stale

# Audit settings
audit:
  pdp:
    max_sleep_interval: 100ms  # Maximum timeout between object.RangeHash requests to the storage node

# Settlement settings
settlement:
  basic_income_rate: 100000000  # Optional: override basic income rate value from network config; applied only in debug mode
  audit_fee: 100000  # Optional: override audit fee value from network config; applied only in debug mode

# LOCODE database
locode:
  db:
    path: /locode/db  # Path to UN/LOCODE database file
```
3. Then restart IR with 
```
docker-compose -f services/ir/docker-compose.yml up -d
```
4. IR ended in an infinite loop:
```
2023-12-08T21:32:55.290Z        info    deploy/deploy.go:353    synchronizing Proxy contract with the chain...
2023-12-08T21:32:55.290Z        info    deploy/contracts.go:170 reading on-chain state of the contract by NNS domain name...    {"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs"}
2023-12-08T21:32:55.298Z        info    deploy/contracts.go:305 sending new Notary request updating the contract...     {"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs"}
2023-12-08T21:32:55.301Z        error   deploy/contracts.go:312 failed to send Notary request updating the contract, will try again later       {"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs", "error": "failed to submit notary request: Expired transaction (-510) - transaction has expired: ValidUntilBlock = 303, current height = 303"}
2023-12-08T21:32:55.495Z        info    deploy/util.go:86       new block arrived       {"height": 304}
2023-12-08T21:32:55.497Z        info    deploy/notary.go:977    enough funds on the notary balance, deposit is not needed       {"balance": "875995719342"}
2023-12-08T21:32:56.495Z        info    deploy/util.go:86       new block arrived       {"height": 305}
2023-12-08T21:32:56.496Z        info    deploy/notary.go:977    enough funds on the notary balance, deposit is not needed       {"balance": "875995719342"}
2023-12-08T21:32:57.302Z        info    deploy/contracts.go:170 reading on-chain state of the contract by NNS domain name...    {"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs"}
2023-12-08T21:32:57.308Z        info    deploy/contracts.go:305 sending new Notary request updating the contract...     {"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs"}
2023-12-08T21:32:57.311Z        error   deploy/contracts.go:312 failed to send Notary request updating the contract, will try again later       {"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs", "error": "failed to submit notary request: Expired transaction (-510) - transaction has expired: ValidUntilBlock = 303, current height = 305"}
2023-12-08T21:32:57.496Z        info    deploy/util.go:86       new block arrived       {"height": 306}
....
2023-12-08T21:34:09.983Z	info	deploy/contracts.go:170	reading on-chain state of the contract by NNS domain name...	{"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs"}
2023-12-08T21:34:09.989Z	info	deploy/contracts.go:305	sending new Notary request updating the contract...	{"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs"}
2023-12-08T21:34:09.992Z	error	deploy/contracts.go:312	failed to send Notary request updating the contract, will try again later	{"contract": "NeoFS Notary Proxy", "domain": "proxy.neofs", "error": "failed to submit notary request: Expired transaction (-510) - transaction has expired: ValidUntilBlock = 303, current height = 378"}
```

What I expect here is that IR container should be restarted and contracts versions should be updated on an existing chain.

**Comment by roman-khimov** [comment]
Hashes won't change, that's expected and that's perfectly fine.

**Comment by evgeniiz321** [comment]
Ok, we can close issue then. Autoupdating was successful.
