### ISSUE TITLE
legacy builder is deprecated, install the buildx component to build images with BuildKit

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#3006]
```
% make images 
⇒ Build NeoFS storage docker image 
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/
```

**Comment by roman-khimov** [comment]
Wow, I'm surprised we still have it here. GH workflows don't use `make images` though, so we just need to transfer proper incantations from them into Makefile.

**Comment by End-rey** [comment]
It says [here](https://docs.docker.com/engine/deprecated/#legacy-builder-for-linux-images) that docker uses `Buildx` by default since version 23.0. And [here](https://docs.docker.com/engine/deprecated/#legacy-builder-fallback) it says that you need to update your version, or all I can do is set the value `DOCKER_BUILDKIT=1`, but the Buildx component is need to be installed.

**Comment by roman-khimov** [comment]
We have current versions, we just need to rework commands to get rid of this warning (see GH workflow for images).
