### ISSUE TITLE
Possible deadlock in blobstor

### ISSUE THREAD

**Issue by fyrchik** [nspcc-dev/neofs-node#481]
Currently active blobovnicza is closed on eviction from LRU cache https://github.com/nspcc-dev/neofs-node/blob/master/pkg/local_object_storage/blobstor/blobovnicza.go#L83 . Because eviction can be done on `Add` to cache, we first take the LRU cache mutex (1) and then `activeMtx` (2).

Now consider `updateAndGet` https://github.com/nspcc-dev/neofs-node/blob/master/pkg/local_object_storage/blobstor/blobovnicza.go#L730 . Here we first take `activeMtx` on write and then remove item from opened cache (this needs mutex (1)).

Because first mutiexes in both cases are taken exclusively, this can lead to a deadlock. We need to investigate if this is really the case and fix it.

**Comment by alexvanin** [comment]
Maybe related: https://github.com/nspcc-dev/neofs-node/pull/246

**Comment by alexvanin** [comment]
As the simplest and efficient solution, we've decided to try using single-thread simple LRU cache and manage locks externally, because blobovnicza requires deep control on evicting and closing bolt db instances.

The other option is keep LRU cache but use it after releasing all external locks (`activeMtx`, `openMtx`).
