### ISSUE TITLE
Support multiple addresses

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#607]
Related https://github.com/nspcc-dev/neofs-api/issues/160

- [ ] Multiple `NODE_ADDRESS` and `GRPC_ENDOINT` addresses should be supported in config.
- [ ] Run node on all provided gRPC endpoints.
- [ ] Announce all provided node addresses.
- [ ] Iterate over sorted* list of endpoints in client cache until you establish connection.

* Sorted list is a list with all TLS endpoints before others.

**Comment by cthulhu-rider** [comment]
We need to recognize `Client`'s connection failures. I can suggest two approaches.
#### 1. Dedicated `Open` or `Init` method
Before any RPC caller should call the method to establish the connection. In this approach we need to think about how `Client` behaves if connection was provided to constructor (e.g. check status). Any RPC should once do pre-opening in order to save previous behavior.
#### 2. Dedicated connection errors
Define typed `error` which can be returned from any RPC method. Check the error when we iterate over all per-address `Client`s.


As for me, 2 is clearer, but 1 also has a place to be.

**Comment by alexvanin** [comment]
> 1. Dedicated Open or Init method

Looks like protocol version handshake becomes handy there.
