### ISSUE TITLE
Log UVB and fallback time when sending notary transaction

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#677]
It will be convenient to track notary invocation failures by looking for fallback transaction. Unfortunately we don't know how to monitor them. As the simplest solution we can log `UntilValidBlock` and fallback valid for time to calculate expected block with fallback transaction.

**Comment by roman-khimov** [comment]
If you had created a notary request you know its main transaction VUB value for sure. That value is the most important here because if the main transaction doesn't get into the blockchain before this block you can be sure it won't ever do that. You don't need to wait for fallback transaction to be accepted, it doesn't make any difference for you (and fallback can be delayed too), VUB is the ultimate timeout anyway, so track it and make appropriate actions if it expires.
