### ISSUE TITLE
After DENY is set for an operation in eACL, the operation can be performed

### ISSUE THREAD

**Issue by EliChin** [nspcc-dev/neofs-node#949]
## Expected Behavior
After we set an eACL using filters with `$Object:` prefix with `Access=DENY` for `Role=OTHERS` for any operations, we expect errors while trying to execute these operations by other user, i.e `GETRANGEHASH` operation.

## Current Behavior
After we set an eACL that denies all operations for other user, the expected error does not occur. `Get Range Hash` can be performed.

## Steps to Reproduce (for bugs)
1. Create public container
2. Put an object to the container
3. Check if this object can be got by other user, expect success
4. Get the object's header
5. Get the relevant attributes with the values from it to further set them as fa filter for eACL rules
6. Set eACL for the container that denies all operations with the objects that match the given filter.
7. Try to get range hash.

## Your Environment
* Version used: neofs-cli 0.26.0, neofs-ir 0.26.0, neofs-node 0.26.0, neo-go 0.97.3

## Log
https://http.testnet.fs.neo.org/HRwMbQkp9j2UcGFto47ngDLduVBV9W4pV8ULESYxLxpr/log.html
![Screenshot from 2021-10-29 11-55-19](https://user-images.githubusercontent.com/70199136/139406673-80761614-4aa4-472e-8806-c948507e07dc.png)

**Comment by alexvanin** [comment]
Seems that you use `$Object:payloadLength` filter in eACL. This filter is not quite suitable for `RangeHash` operation.
$Object:|GET|HEAD|PUT|DELETE|SEARCH|RANGE|RANGEHASH|
|---|---|---|---|---|---|---|---|
|version|v|v|v|-|-|-|-|
|objectID|v|v|v|v|-|v|v|
|containerID|v|v|v|v|v|v|v|
|ownerID|v|v|v|-|-|-|-|
|creationEpoch|v|v|v|-|-|-|-|
|payloadLength|v|v|v|-|-|-|-|
|payloadHash|v|v|v|-|-|-|-|
|objectType|v|v|v|-|-|-|-|
|homomorphicHash|v|v|v|-|-|-|-|
|// User headers|v|v|v|-|-|-|-|


Then you may ask why `Delete` and `Range` operation failed if they are pretty much the same in terms of eACL policy rights. They fail because they produce `HEAD` requests, which can be denied by `$Object:payloadLength` rule.

I guess we can't do anything about it right now, those cases are kinda Undefined Behavior.

**Comment by EliChin** [comment]
@alexvanin In the log that I've attached `RangeHash` operation first fails when using `$Object:ownerID`. According to the table, it is not suitable for `RangeHash` operation too.

**Comment by aprasolova** [comment]
https://github.com/nspcc-dev/neofs-spec/issues/62
https://github.com/nspcc-dev/neofs-node/issues/951
