### ISSUE TITLE
Refactor subnet processor

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#991]
Initial implementation in https://github.com/nspcc-dev/neofs-node/pull/986 does not define subnet processor in subnet package. Inner ring application processes all events in processor instances, which allows to separate business logic of event handling from declarations and state storage in Inner Ring server. Subnet contract is not any different from other contracts so it will be consistent if it will be implemented the same way.

After that, subnet processor should listen `RemoveNode` event. Now (https://github.com/nspcc-dev/neofs-node/pull/987) `RemoveNode` event is processed by netmap processor. This is not quite correct, because every processor parses events from corresponding contract. We don't want to mix handlers of different events in the same processor to keep the structure simple.

**Comment by cthulhu-rider** [comment]
Even taking on trust the usefulness of these changes, it makes sense to provide public event handlers from the processor, and encapsulate the processing queue in the processor and write the results to the chain. Dragging a group of parameters in order to pull them back through public methods `ListenerX` IMO seems to me to be an overhead.

In total, I would generally revise the architecture of the processors, rather than just drive listening to the Subnet contract into the same pattern.
